name: linxz

services:
  linxz:
    image: ngregrichardson/linxz
    container_name: linxz
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BASE_URL
      - DB_URL
      - DB_AUTH_TOKEN
      - NEXT_PUBLIC_CFTS_SITE_KEY
      - CFTS_SECRET_KEY