name: Release

on:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v4
              id: release
              with:
                token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
                release-type: node